f=input("give me first number:")
t=input("give me second number:")
print("thank you!")
k= int(f) + int(t) 
kd= int(f) - int(t) 
ks= int(f) / int(t) 
ka= int(f) * int(t) 
print (f +"+"+ t + "=" + str(k) )
print (f +"-"+ t + "=" + str(kd) )
print (f +"/"+ t + "=" + str(ks) )
print (f +"*"+ t + "=" + str(ka) )